/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernorAlpha } from "./GovernorAlpha";
export type { TimelockInterface } from "./TimelockInterface";
export type { VotingTokenInterface } from "./VotingTokenInterface";
