/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as abstract from "./abstract";
export type { abstract };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { GenesisAllocation } from "./GenesisAllocation";
export type { IncentiveAllocation } from "./IncentiveAllocation";
export type { TcpAllocation } from "./TcpAllocation";
