/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ITcpAllocationInterface extends utils.Interface {
  functions: {
    "getTokens(address,uint128)": FunctionFragment;
    "incentiveGuardian()": FunctionFragment;
    "increaseAllocation(address,uint128)": FunctionFragment;
    "lockTokensIntoDao(address,uint128,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getTokens",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incentiveGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllocation",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockTokensIntoDao",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "incentiveGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockTokensIntoDao",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ITcpAllocation extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITcpAllocationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getTokens(
      dest: string,
      count: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    incentiveGuardian(overrides?: CallOverrides): Promise<[string]>;

    increaseAllocation(
      allocatee: string,
      count: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lockTokensIntoDao(
      dest: string,
      count: BigNumberish,
      lockDurationMonths: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getTokens(
    dest: string,
    count: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  incentiveGuardian(overrides?: CallOverrides): Promise<string>;

  increaseAllocation(
    allocatee: string,
    count: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lockTokensIntoDao(
    dest: string,
    count: BigNumberish,
    lockDurationMonths: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getTokens(
      dest: string,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    incentiveGuardian(overrides?: CallOverrides): Promise<string>;

    increaseAllocation(
      allocatee: string,
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    lockTokensIntoDao(
      dest: string,
      count: BigNumberish,
      lockDurationMonths: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getTokens(
      dest: string,
      count: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    incentiveGuardian(overrides?: CallOverrides): Promise<BigNumber>;

    increaseAllocation(
      allocatee: string,
      count: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lockTokensIntoDao(
      dest: string,
      count: BigNumberish,
      lockDurationMonths: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getTokens(
      dest: string,
      count: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    incentiveGuardian(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    increaseAllocation(
      allocatee: string,
      count: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lockTokensIntoDao(
      dest: string,
      count: BigNumberish,
      lockDurationMonths: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
